# Generated by Django 3.1.5 on 2021-03-04 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ec', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='pants',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ec.pants'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='shirts',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ec.shirts'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='shoes',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ec.shoes'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='cart',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ec.cart'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='jackets',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ec.jackets'),
        ),
    ]
