# Generated by Django 3.1.5 on 2021-03-09 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ec', '0004_auto_20210309_1430'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchasehistory',
            old_name='purchase_detail',
            new_name='cart_item',
        ),
    ]
