# Generated by Django 3.1.5 on 2021-03-09 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ec', '0005_auto_20210309_1432'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchasehistory',
            name='jackets',
        ),
        migrations.RemoveField(
            model_name='purchasehistory',
            name='pants',
        ),
        migrations.RemoveField(
            model_name='purchasehistory',
            name='shirts',
        ),
        migrations.RemoveField(
            model_name='purchasehistory',
            name='shoes',
        ),
    ]
