# Generated by Django 3.1.5 on 2021-03-09 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ec', '0007_auto_20210309_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasehistory',
            name='jackets_history',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ec.jackets'),
        ),
    ]
