# Generated by Django 3.1.5 on 2021-03-09 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ec', '0008_purchasehistory_jackets_history'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchasehistory',
            name='cart_history',
        ),
    ]
