# Generated by Django 3.1.5 on 2021-03-09 17:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ec', '0009_remove_purchasehistory_cart_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasehistory',
            name='date_added',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchasehistory',
            name='purchase_user',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='purchasehistory',
            name='quantity',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
