# Generated by Django 3.1.5 on 2021-03-09 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ec', '0010_auto_20210310_0232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasehistory',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
