# Generated by Django 3.1.5 on 2021-03-12 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ec', '0011_auto_20210310_0239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jackets',
            name='jacket_price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='pants',
            name='pant_price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='shirts',
            name='shirt_price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='shoes',
            name='shoe_price',
            field=models.IntegerField(),
        ),
    ]
