# Generated by Django 3.1.5 on 2021-03-17 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ec', '0012_auto_20210313_0306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jackets',
            name='jacket_size',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='pants',
            name='pant_size',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='shirts',
            name='shirt_size',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='shoes',
            name='shoe_size',
            field=models.CharField(max_length=2, null=True),
        ),
    ]
