# Generated by Django 3.1.5 on 2021-03-24 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ec', '0017_customuser_coupon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='coupon',
            field=models.IntegerField(default=0),
        ),
    ]
