# Generated by Django 3.1.5 on 2021-03-30 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ec', '0021_auto_20210329_1741'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='cart_coupon',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='cart_sum',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='cart_coupon',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='cart_sum',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='purchasehistory',
            name='use_coupon',
            field=models.IntegerField(default=0),
        ),
    ]
