# Generated by Django 3.1.5 on 2021-03-30 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ec', '0022_auto_20210330_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='cart_coupon',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='cart_sum',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
