# Generated by Django 3.1.5 on 2021-03-30 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ec', '0023_auto_20210330_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasehistory',
            name='purchase_sum',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='purchasehistory',
            name='use_coupon',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
